### ISSUE TITLE
Allow console command specific extra options

### ISSUE THREAD

**Issue by bjko** [ezsystems/ezplatform-cron#12]
add an additional parameter with which you can add console command specific parameters e.g. for console command  cleanup versions or check url

- for ezplatform:check-urls the option "--quiet"
- for ezplatform:content:cleanup-versions the options "--keep --status=draft"

currently you are not able to add this options in the cron config

**Comment by andrerom** [comment]
Quiet and verbose are global symfony options, so those should probably rather be passed on from the cron command to the underlying command. But for all other custom arguments: completely agree 👍

**Comment by bjko** [comment]
@andrerom what are the plans to extend this?

**Comment by andrerom** [comment]
@bjko Currently none, but @SylvainGuittard might want to put it on the roadmap.

**Comment by bjko** [comment]
@andrerom @SylvainGuittard since we need this while deploying our solutions we did a PR for this: https://github.com/ezsystems/ezplatform-cron/pull/13

we would be happy if you could release and implement this on short notice

**Comment by lserwatka** [comment]
Closing. We are using JIRA for issues reports. https://jira.ez.no/
