### ISSUE TITLE
Bundle will probably not work optimally on platform.sh

### ISSUE THREAD

**Issue by andrerom** [ezsystems/ezplatform-cron#4]
This bundle currently seems to require to run every minute, with no gaps.

This won't work on Platform.sh:
> The minimum interval between cron runs is 5 minutes, even if specified as less. Additionally, a variable delay is added to each cron job in each project in order to prevent host overloading should every project try to run their nightly tasks at the same time. Your crons will not run exactly at the time that you specify, but will be delayed by 0-300 seconds.

> A single application container may have any number of cron tasks configured, but only one may be running at a time. That is, if a cron task fires while another cron task is still running it will pause and then continue normally once the first has completed.

ref: https://docs.platform.sh/configuration/app/cron.html#cron-jobs

**Comment by lserwatka** [comment]
Closing. We are using JIRA for issues reports. https://jira.ez.no/
